channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - conda-forge::pulp
  - ipykernel
  - pandas
  - toml
  - seaborn
